#!/bin/bash

if [ -f l4.data ]
then
  rm l4.data
  echo "Файл l4.data удалён"
fi

test/make-result-stress-test
grep "на 200000 подписки" test/stress-test.out > /dev/null

if [ $? -ne 0 ]
then
  echo -e "\033[1mОшибка при выполнении теста test/make-result-stress-test\033[0m"
  exit 1
fi
