#!/bin/bash

if [ -f l3.data ]
then
  rm l3.data
  echo "Файл l3.data удалён"
fi

test/make-result-stress-test
diff test/samples/stress-test.sample test/stress-test.out

if [ $? -ne 0 ]
then
  echo -e "\033[1mОшибка при выполнении теста test/make-result-stress-test\033[0m"
  exit 1
fi
