#!/bin/bash

if [ -f l3.data ]
then
  rm l3.data
  echo "Файл l3.data удалён"
fi

test/make-result-lab
diff test/samples/lab.sample test/lab.out

if [ $? -ne 0 ]
then
  echo -e "\033[1mОшибка при выполнении теста test/make-result-lab\033[0m"
  exit 1
fi

test/make-result-stressgen
diff test/samples/stressgen.sample test/stressgen.out

if [ $? -ne 0 ]
then
  echo -e "\033[1mОшибка при выполнении теста test/make-result-stressgen\033[0m"
  exit 1
fi
