name: hw_ci

on:
  push:

  pull_request:


jobs:
  before-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: before-script
        run: |
          export DEBIAN_FRONTEND=noninteractive
          export TZ=Europe/Moscow

  build-and-test-code:
    runs-on: ubuntu-latest
    needs: before-script
    
    steps:
      - uses: actions/checkout@v3
      - name: Build code
        run: |
          # Устанавливаем пакеты
          sudo apt-get update
          sudo apt-get -y install gcc g++
          sudo apt-get -y install make 
          # Собираем
          cd hw
          g++ ./main.cpp -o main -std=c++17

      - name: Tests
        run: |
          # Автотесты
          cd hw
          sudo chmod +x ./test*.*
          sudo chmod +x ./main
          ./main > ./test-result.txt
          diff ./test-sample.txt ./test-result.txt

      - name: Documentation 
        run: |
          cd hw
          sudo apt-get -y install doxygen
          doxygen Doxyfile.cfg

      - name: Upload coverage report
        run: |
          cd hw
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          