name: l2_ci

on: [push, pull_request]

jobs:
  before-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: before-script
        run: |
          export DEBIAN_FRONTEND=noninteractive
          export TZ=Europe/Moscow

  build-and-test-code:
    runs-on: ubuntu-latest
    needs: before-script
    
    steps:
      - uses: actions/checkout@v3
      - name: Build code
        run: |
          # Устанавливаем пакеты
          sudo apt-get update
          sudo apt-get -y install gcc g++
          sudo apt-get -y install make 
          # Собираем
          cd l2
          sudo chmod +x ./configure
          ./configure
          make

      - name: Test
        run: |
          # Автотесты
          cd l2
          sudo chmod +x ./test/test*.*
          sudo chmod +x ./test/make-result
          ./test/make-result
          diff ./test/test-result.sample ./test/test-result.out

      - name: Documentation 
        run: |
          cd l2
          sudo apt-get -y install doxygen
          doxygen doc/Doxyfile.cfg

      - name: Make coverage report
        run: |
          # Устанавливаем пакеты
          sudo apt-get -y install gcc g++ make lcov
          # Прогоняем тесты
          cd l2
          sudo chmod +x ./test/make-result
          ./test/make-result
          # Строим отчёт покрытия
          lcov -t "lab" -o ./coverage/lab.info -c -d . --no-external

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lab.info
